### ISSUE TITLE
Impleament of Bagging

### ISSUE THREAD

**Issue by SilvesterHsu** [AaronX121/Ensemble-Pytorch#1]
In the code of `BaggingClassifier` [line 28](https://github.com/AaronX121/Ensemble-Pytorch/blob/master/ensemble/baggingclassifier.py#L28), the size should not be multiplied with `0.632`.
```python
sampled_mask = torch.randint(high=batch_size, size=(int(batch_size*0.632),), dtype=torch.int64)
```

The `torch.randint` is a sample method with **replacement**. In other words, duplicate elements will appear in the results

In the case of replacement，
<a href="https://www.codecogs.com/eqnedit.php?latex=\lim_{m\rightarrow&space;\infty&space;}(1-\frac{1}{m})^m&space;=&space;\frac{1}{e}&space;\approx&space;0.368" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\lim_{m\rightarrow&space;\infty&space;}(1-\frac{1}{m})^m&space;=&space;\frac{1}{e}&space;\approx&space;0.368" title="\lim_{m\rightarrow \infty }(1-\frac{1}{m})^m = \frac{1}{e} \approx 0.368" /></a>

To verify whether it is with replacement,
```python
batch_size = 100000
element_set = set(torch.randint(high=batch_size, size=(batch_size,)).numpy())
print(1 - len(element_set)/batch_size) #0.368
```
Subsequently, we can get an approximate theoretical value of about 0.368. This means that the elements obtained through `torch.randint` only account for 63.2% of the total elements.

Therefore, it should be corrected as
```python
sampled_mask = torch.randint(high=batch_size, size=(int(batch_size),), dtype=torch.int64)
```

**Comment by AaronX121** [comment]
Thanks for your clarifications on `torch.randint`. I will fix it !
