### ISSUE TITLE
No module named `torchensemble.method`

### ISSUE THREAD

**Issue by JosephBChoi** [AaronX121/Ensemble-Pytorch#2]
@AaronX121, Dear AaronX121, 

I tried to follow the code snippet provided on the README.md, but it complains with a run-time error of `ModuleNotFoundError: No module named 'torchensemble.methd'`. 

The run-time error seems to make sense since there is no `method` function inside of the `torchensemble` folder. 

Could you help me how to fix or get around this issue?

**Comment by AaronX121** [comment]
The keyword `method` in README.md indicates one of {`fusion`, `voting`, `bagging`, `gradient_boosting`}. You can see scripts in `/examples` for details on how to use.

Let me know if there is still a problem :-)

**Comment by AaronX121** [comment]
Feel free to open another issue if you have any problem.
