### ISSUE TITLE
Requirements.txt versions

### ISSUE THREAD

**Issue by Zackhardtoname** [AaronX121/Ensemble-Pytorch#3]
Could you add the version numbers

**Comment by AaronX121** [comment]
Thanks for reporting @Zackhardtoname, I will add the minimum requirements latter.

In addition, feel free to tell me if it has any problem under your current package environment. In my practice, it works well from PyTorch 0.4 to the latest 1.7.

**Comment by Zackhardtoname** [comment]
That's definitely good to know! So far it's really helpful!
